<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\MuscleGroup;
use Illuminate\Database\Seeder;

/**
 * The starting exercise library.
 *
 * `equipment` and the entries of `secondary_muscles` are stored as stable slugs,
 * never as Arabic text — the UI translates them. `youtube_url` and `media_path`
 * stay null: real media is uploaded from the admin panel.
 */
class ExerciseSeeder extends Seeder
{
    /**
     * muscle slug => list of exercises.
     *
     * @var array<string, list<array{ar: string, en: string, slug: string, equipment: string, difficulty: string, secondary: list<string>, desc_ar: string, desc_en: string}>>
     */
    private const EXERCISES = [
        'chest' => [
            [
                'ar' => 'ضغط بنش بالبار',
                'en' => 'Barbell Bench Press',
                'slug' => 'barbell-bench-press',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['triceps', 'shoulders'],
                'desc_ar' => 'استلقِ على البنش وأنزل البار إلى منتصف الصدر ثم ادفعه للأعلى حتى امتداد المرفقين. الخطأ الشائع ارتداد البار من الصدر وفتح المرفقين بزاوية قائمة.',
                'desc_en' => 'Lie on a flat bench, lower the bar to mid-chest under control, then press it back to lockout. The common mistake is bouncing the bar off the chest and flaring the elbows to ninety degrees.',
            ],
            [
                'ar' => 'ضغط بنش مائل بالدمبل',
                'en' => 'Incline Dumbbell Press',
                'slug' => 'incline-dumbbell-press',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['triceps', 'shoulders'],
                'desc_ar' => 'على بنش مائل ثلاثين درجة، ادفع الدمبل من مستوى الصدر العلوي للأعلى دون اصطدام الدمبلين. الخطأ الشائع رفع زاوية البنش كثيرًا فينتقل الحمل إلى الكتف.',
                'desc_en' => 'On a bench set to about thirty degrees, press the dumbbells from upper-chest level without clashing them at the top. The common mistake is setting the bench too steep, which shifts the work onto the front delts.',
            ],
            [
                'ar' => 'ضغط صدر على الجهاز',
                'en' => 'Chest Press Machine',
                'slug' => 'chest-press-machine',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => ['triceps', 'shoulders'],
                'desc_ar' => 'اجلس بحيث يكون المقبض بمحاذاة منتصف الصدر وادفع للأمام حتى امتداد المرفقين دون قفلهما بعنف. الخطأ الشائع رفع الكتف عن المسند أثناء الدفع.',
                'desc_en' => 'Sit so the handles line up with mid-chest and press forward to near lockout without slamming the elbows. The common mistake is letting the shoulders lift off the pad as you push.',
            ],
            [
                'ar' => 'تفتيح بالدمبل على بنش مسطح',
                'en' => 'Dumbbell Fly',
                'slug' => 'dumbbell-fly',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['shoulders'],
                'desc_ar' => 'افتح الذراعين بقوس واسع مع انحناء ثابت في المرفق ثم اجمعهما فوق الصدر. الخطأ الشائع ثني المرفق أثناء الحركة فتتحول إلى ضغط.',
                'desc_en' => 'Open the arms in a wide arc with a fixed slight elbow bend, then bring them together over the chest. The common mistake is bending the elbows mid-rep, which turns the fly into a press.',
            ],
            [
                'ar' => 'تفتيح بالكيبل من أعلى',
                'en' => 'Cable Crossover',
                'slug' => 'cable-crossover',
                'equipment' => 'cable',
                'difficulty' => 'intermediate',
                'secondary' => ['shoulders'],
                'desc_ar' => 'من بكرة عالية، اسحب المقبضين إلى الأمام وللأسفل حتى يتقاطعا أمام البطن مع ضغط الصدر. الخطأ الشائع الاستعانة بالجذع بالميل للأمام مع كل عدة.',
                'desc_en' => 'From high pulleys, draw the handles down and forward until they cross in front of the abdomen, squeezing the chest. The common mistake is rocking the torso forward on every rep.',
            ],
            [
                'ar' => 'غطس للصدر على المتوازي',
                'en' => 'Chest Dip',
                'slug' => 'chest-dip',
                'equipment' => 'bodyweight',
                'difficulty' => 'advanced',
                'secondary' => ['triceps', 'shoulders'],
                'desc_ar' => 'مِل بالجذع للأمام قليلًا وانزل حتى يصل الكتف لمستوى المرفق ثم ادفع للأعلى. الخطأ الشائع النزول أعمق من المدى المريح فيتحمّل مفصل الكتف.',
                'desc_en' => 'Lean the torso slightly forward and descend until the shoulder reaches elbow height, then press back up. The common mistake is dropping deeper than a comfortable range and loading the shoulder joint.',
            ],
            [
                'ar' => 'ضغط أرضي',
                'en' => 'Push-Up',
                'slug' => 'push-up',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'secondary' => ['triceps', 'core'],
                'desc_ar' => 'ثبّت الجسم بخط مستقيم من الكعب إلى الرأس وانزل حتى يقترب الصدر من الأرض. الخطأ الشائع هبوط الورك أو رفعه بدل بقاء الجسم بخط واحد.',
                'desc_en' => 'Hold the body in a straight line from heel to head and lower until the chest is close to the floor. The common mistake is letting the hips sag or pike instead of staying in one line.',
            ],
        ],

        'back' => [
            [
                'ar' => 'سحب أمامي بالكيبل',
                'en' => 'Lat Pulldown',
                'slug' => 'lat-pulldown',
                'equipment' => 'cable',
                'difficulty' => 'beginner',
                'secondary' => ['biceps', 'forearms'],
                'desc_ar' => 'اسحب البار إلى أعلى الصدر مع خفض لوح الكتف أولًا ثم عد للأعلى بتحكّم. الخطأ الشائع سحب البار خلف الرقبة أو الميل بالجذع للخلف بشدة.',
                'desc_en' => 'Pull the bar to the upper chest, initiating by depressing the shoulder blades, then return under control. The common mistake is pulling behind the neck or leaning the torso far back.',
            ],
            [
                'ar' => 'عقلة',
                'en' => 'Pull-Up',
                'slug' => 'pull-up',
                'equipment' => 'bodyweight',
                'difficulty' => 'advanced',
                'secondary' => ['biceps', 'forearms'],
                'desc_ar' => 'اسحب جسمك حتى يتجاوز الذقن مستوى البار مع إبقاء الأكتاف بعيدة عن الأذنين. الخطأ الشائع المرجحة بالأرجل لاستكمال العدة.',
                'desc_en' => 'Pull yourself up until the chin clears the bar while keeping the shoulders away from the ears. The common mistake is kipping with the legs to finish the rep.',
            ],
            [
                'ar' => 'تجديف بالبار منحنيًا',
                'en' => 'Barbell Bent-Over Row',
                'slug' => 'barbell-bent-over-row',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['biceps', 'core'],
                'desc_ar' => 'انحنِ بالجذع قرابة خمس وأربعين درجة واسحب البار إلى أسفل الصدر مع شد لوحي الكتف. الخطأ الشائع تقويس الظهر السفلي أو الوقوف تدريجيًا مع كل عدة.',
                'desc_en' => 'Hinge the torso to about forty-five degrees and row the bar to the lower chest while squeezing the shoulder blades. The common mistake is rounding the lower back or standing up gradually with each rep.',
            ],
            [
                'ar' => 'تجديف بالدمبل بذراع واحدة',
                'en' => 'One-Arm Dumbbell Row',
                'slug' => 'one-arm-dumbbell-row',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['biceps'],
                'desc_ar' => 'ارتكز بيد وركبة على البنش واسحب الدمبل إلى جانب الخصر مع بقاء الكتفين متوازيين. الخطأ الشائع لفّ الجذع لرفع وزن أثقل.',
                'desc_en' => 'Brace one hand and knee on the bench and row the dumbbell to the side of the waist with the shoulders level. The common mistake is twisting the torso to move a heavier weight.',
            ],
            [
                'ar' => 'تجديف أرضي بالكيبل',
                'en' => 'Seated Cable Row',
                'slug' => 'seated-cable-row',
                'equipment' => 'cable',
                'difficulty' => 'beginner',
                'secondary' => ['biceps', 'forearms'],
                'desc_ar' => 'اسحب المقبض إلى البطن مع بقاء الظهر مشدودًا وثابتًا، ثم مدّ الذراعين ببطء. الخطأ الشائع الميل للخلف بالجذع لاستعمال وزن الجسم.',
                'desc_en' => 'Draw the handle to the abdomen with a braced, steady torso, then extend the arms slowly. The common mistake is rocking backwards to use bodyweight as momentum.',
            ],
            [
                'ar' => 'رفعة ميتة بالبار',
                'en' => 'Barbell Deadlift',
                'slug' => 'barbell-deadlift',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'secondary' => ['legs', 'core', 'forearms'],
                'desc_ar' => 'ارفع البار من الأرض بدفع القدمين والظهر مشدود حتى الوقوف الكامل بامتداد الورك. الخطأ الشائع رفع الورك قبل الصدر فينتقل الحمل كله إلى أسفل الظهر.',
                'desc_en' => 'Drive through the feet with a braced spine and stand up until the hips are fully extended. The common mistake is letting the hips rise before the chest, dumping the load onto the lower back.',
            ],
            [
                'ar' => 'سحب مستقيم الذراعين بالكيبل',
                'en' => 'Straight-Arm Pulldown',
                'slug' => 'straight-arm-pulldown',
                'equipment' => 'cable',
                'difficulty' => 'intermediate',
                'secondary' => ['core'],
                'desc_ar' => 'بذراعين شبه مستقيمتين، ادفع البار من مستوى الوجه إلى الفخذين بقوس واسع. الخطأ الشائع ثني المرفق فتتحول الحركة إلى تمديد ترايسبس.',
                'desc_en' => 'With near-straight arms, sweep the bar from face height down to the thighs in a wide arc. The common mistake is bending the elbows, which turns it into a triceps pushdown.',
            ],
        ],

        'shoulders' => [
            [
                'ar' => 'ضغط كتف بالبار واقفًا',
                'en' => 'Standing Overhead Press',
                'slug' => 'standing-overhead-press',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['triceps', 'core'],
                'desc_ar' => 'ادفع البار من أعلى الصدر إلى فوق الرأس مع شد البطن ومنع تقوّس الظهر. الخطأ الشائع الدفع بالأرجل والميل للخلف لتمرير الوزن.',
                'desc_en' => 'Press the bar from the upper chest to overhead with the abdomen braced and no arch in the lower back. The common mistake is leaning back and driving with the legs to get the weight up.',
            ],
            [
                'ar' => 'ضغط كتف بالدمبل جالسًا',
                'en' => 'Seated Dumbbell Shoulder Press',
                'slug' => 'seated-dumbbell-shoulder-press',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['triceps'],
                'desc_ar' => 'اجلس بظهر مسنود وادفع الدمبل من مستوى الأذن حتى امتداد المرفقين. الخطأ الشائع النزول بالدمبل أقل من اللازم فيقصر المدى.',
                'desc_en' => 'Sit with the back supported and press the dumbbells from ear height to full elbow extension. The common mistake is cutting the descent short and losing range of motion.',
            ],
            [
                'ar' => 'رفرفة جانبية بالدمبل',
                'en' => 'Dumbbell Lateral Raise',
                'slug' => 'dumbbell-lateral-raise',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'ارفع الدمبل إلى الجانب حتى مستوى الكتف مع انحناء بسيط في المرفق. الخطأ الشائع استعمال وزن ثقيل ورفعه بمرجحة من الورك.',
                'desc_en' => 'Raise the dumbbells out to the side up to shoulder height with a slight elbow bend. The common mistake is going too heavy and swinging the weight up from the hips.',
            ],
            [
                'ar' => 'رفرفة أمامية بالدمبل',
                'en' => 'Dumbbell Front Raise',
                'slug' => 'dumbbell-front-raise',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['chest'],
                'desc_ar' => 'ارفع الدمبل أمامك حتى مستوى الكتف ثم أنزله ببطء. الخطأ الشائع الارتداد بالجذع للخلف عند نهاية الرفع.',
                'desc_en' => 'Raise the dumbbells in front of you to shoulder height, then lower them slowly. The common mistake is leaning the torso back at the top of the lift.',
            ],
            [
                'ar' => 'رفرفة خلفية منحنيًا',
                'en' => 'Bent-Over Reverse Fly',
                'slug' => 'bent-over-reverse-fly',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['back'],
                'desc_ar' => 'انحنِ من الورك وافتح الذراعين للجانبين مع ضغط لوحي الكتف. الخطأ الشائع رفع الذراعين بثني المرفق فتشتغل عضلة الظهر بدل مؤخرة الكتف.',
                'desc_en' => 'Hinge at the hips and open the arms out to the sides while squeezing the shoulder blades. The common mistake is bending the elbows and turning it into a row for the lats.',
            ],
            [
                'ar' => 'سحب عالٍ للوجه بالكيبل',
                'en' => 'Cable Face Pull',
                'slug' => 'cable-face-pull',
                'equipment' => 'cable',
                'difficulty' => 'intermediate',
                'secondary' => ['back'],
                'desc_ar' => 'اسحب الحبل نحو الجبهة مع تباعد اليدين ودوران خارجي للكتف. الخطأ الشائع السحب منخفضًا إلى الصدر بدل مستوى الوجه.',
                'desc_en' => 'Pull the rope toward the forehead, spreading the hands and externally rotating the shoulders. The common mistake is pulling low to the chest instead of at face height.',
            ],
            [
                'ar' => 'هزّ الكتفين بالدمبل',
                'en' => 'Dumbbell Shrug',
                'slug' => 'dumbbell-shrug',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['forearms'],
                'desc_ar' => 'ارفع الكتفين للأعلى مباشرة واثبت لحظة ثم أنزلهما ببطء. الخطأ الشائع تدوير الكتف للخلف بدل الرفع العمودي.',
                'desc_en' => 'Lift the shoulders straight up, hold briefly, then lower slowly. The common mistake is rolling the shoulders backwards instead of shrugging vertically.',
            ],
        ],

        'biceps' => [
            [
                'ar' => 'مرجحة بالبار',
                'en' => 'Barbell Curl',
                'slug' => 'barbell-curl',
                'equipment' => 'barbell',
                'difficulty' => 'beginner',
                'secondary' => ['forearms'],
                'desc_ar' => 'ارفع البار بثني المرفق فقط مع بقاء العضد ملاصقًا للجذع. الخطأ الشائع تقديم المرفق للأمام ومرجحة الظهر مع كل عدة.',
                'desc_en' => 'Curl the bar by bending only at the elbow, keeping the upper arm pinned to the torso. The common mistake is drifting the elbows forward and swinging the back on each rep.',
            ],
            [
                'ar' => 'مرجحة بالدمبل بالتناوب',
                'en' => 'Alternating Dumbbell Curl',
                'slug' => 'alternating-dumbbell-curl',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['forearms'],
                'desc_ar' => 'ارفع دمبل واحدًا في كل مرة مع دوران بسيط للمعصم عند القمة. الخطأ الشائع بدء العدة التالية قبل نزول الذراع بالكامل.',
                'desc_en' => 'Curl one dumbbell at a time with a slight wrist rotation at the top. The common mistake is starting the next rep before the arm has fully lowered.',
            ],
            [
                'ar' => 'مرجحة مطرقية',
                'en' => 'Hammer Curl',
                'slug' => 'hammer-curl',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'secondary' => ['forearms'],
                'desc_ar' => 'امسك الدمبل بقبضة محايدة وارفعه دون تدوير المعصم. الخطأ الشائع مرجحة الوزن بدل التحكّم بالنزول.',
                'desc_en' => 'Hold the dumbbells with a neutral grip and curl without rotating the wrist. The common mistake is swinging the weight instead of controlling the descent.',
            ],
            [
                'ar' => 'مرجحة على المسند المائل',
                'en' => 'Preacher Curl',
                'slug' => 'preacher-curl',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['forearms'],
                'desc_ar' => 'ثبّت العضد على المسند المائل وارفع البار دون قفل المرفق في الأسفل. الخطأ الشائع فرد المرفق بالكامل بوزن ثقيل فيتحمّل المفصل.',
                'desc_en' => 'Rest the upper arm on the angled pad and curl the bar without locking the elbow at the bottom. The common mistake is snapping into full extension under a heavy load.',
            ],
            [
                'ar' => 'مرجحة بالكيبل',
                'en' => 'Cable Curl',
                'slug' => 'cable-curl',
                'equipment' => 'cable',
                'difficulty' => 'beginner',
                'secondary' => ['forearms'],
                'desc_ar' => 'قف أمام البكرة السفلية وارفع المقبض بثني المرفق مع شد مستمر. الخطأ الشائع التراجع للخلف بالجسم لمساعدة الرفع.',
                'desc_en' => 'Stand facing the low pulley and curl the handle with constant tension on the muscle. The common mistake is stepping or leaning back to help the lift.',
            ],
        ],

        'triceps' => [
            [
                'ar' => 'تمديد ترايسبس بالكيبل',
                'en' => 'Cable Triceps Pushdown',
                'slug' => 'cable-triceps-pushdown',
                'equipment' => 'cable',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'ادفع المقبض للأسفل حتى امتداد المرفق مع بقاء العضد ثابتًا بجانب الجذع. الخطأ الشائع الميل بالجسم على المقبض لدفع وزن أثقل.',
                'desc_en' => 'Push the handle down to full elbow extension with the upper arm locked at your side. The common mistake is leaning body weight onto the bar to move more load.',
            ],
            [
                'ar' => 'تمديد فوق الرأس بالدمبل',
                'en' => 'Overhead Dumbbell Triceps Extension',
                'slug' => 'overhead-dumbbell-triceps-extension',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['shoulders'],
                'desc_ar' => 'أنزل الدمبل خلف الرأس بمرفق ثابت ثم مدّه للأعلى. الخطأ الشائع فتح المرفقين للخارج فيقلّ الشد على العضلة.',
                'desc_en' => 'Lower the dumbbell behind the head with the elbows fixed, then extend back up. The common mistake is letting the elbows flare out and losing tension.',
            ],
            [
                'ar' => 'ضغط بنش بقبضة ضيقة',
                'en' => 'Close-Grip Bench Press',
                'slug' => 'close-grip-bench-press',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['chest', 'shoulders'],
                'desc_ar' => 'امسك البار بعرض الكتفين وأنزله إلى أسفل الصدر مع مرفق قريب من الجسم. الخطأ الشائع تضييق القبضة أكثر من اللازم فيتألم المعصم.',
                'desc_en' => 'Grip the bar at shoulder width and lower it to the lower chest with the elbows tucked. The common mistake is gripping far too narrow and straining the wrists.',
            ],
            [
                'ar' => 'غطس بين مقعدين',
                'en' => 'Bench Dip',
                'slug' => 'bench-dip',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'secondary' => ['chest', 'shoulders'],
                'desc_ar' => 'ارتكز بيديك على مقعد خلفك وانزل حتى يصنع المرفق زاوية قائمة. الخطأ الشائع النزول عميقًا جدًا مع تقديم الكتف.',
                'desc_en' => 'Support your hands on a bench behind you and lower until the elbows reach ninety degrees. The common mistake is going too deep and letting the shoulders roll forward.',
            ],
            [
                'ar' => 'تمديد ترايسبس بالبار مستلقيًا',
                'en' => 'Lying Triceps Extension',
                'slug' => 'lying-triceps-extension',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['shoulders'],
                'desc_ar' => 'أنزل البار نحو الجبهة بثني المرفق فقط ثم مدّه للأعلى. الخطأ الشائع تحريك العضد للخلف فتتحول الحركة إلى ضغط.',
                'desc_en' => 'Lower the bar toward the forehead by bending only at the elbow, then extend back up. The common mistake is drifting the upper arms back and turning it into a press.',
            ],
        ],

        'legs' => [
            [
                'ar' => 'سكوات خلفي بالبار',
                'en' => 'Barbell Back Squat',
                'slug' => 'barbell-back-squat',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['core', 'back'],
                'desc_ar' => 'ضع البار على أعلى الظهر وانزل بالورك للخلف والأسفل حتى يوازي الفخذ الأرض. الخطأ الشائع رفع الكعب أو انهيار الركبة للداخل عند الصعود.',
                'desc_en' => 'Rack the bar on the upper back and sit down and back until the thighs reach parallel. The common mistake is the heels lifting or the knees caving inward on the way up.',
            ],
            [
                'ar' => 'سكوات أمامي',
                'en' => 'Front Squat',
                'slug' => 'front-squat',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'secondary' => ['core'],
                'desc_ar' => 'احمل البار على مقدمة الكتف بمرفقين مرفوعين وانزل مع بقاء الجذع عموديًا. الخطأ الشائع سقوط المرفقين فينحني الجذع للأمام ويسقط البار.',
                'desc_en' => 'Hold the bar on the front delts with high elbows and descend keeping the torso upright. The common mistake is dropping the elbows, which folds the torso forward and dumps the bar.',
            ],
            [
                'ar' => 'ضغط أرجل على الجهاز',
                'en' => 'Leg Press',
                'slug' => 'leg-press',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => ['core'],
                'desc_ar' => 'ادفع المنصة حتى امتداد الركبة دون قفلها، وانزل حتى تقترب الركبة من الصدر. الخطأ الشائع رفع أسفل الظهر عن المسند في النزول العميق.',
                'desc_en' => 'Press the platform to near lockout without snapping the knees, and lower until the knees approach the chest. The common mistake is the lower back lifting off the pad at the bottom.',
            ],
            [
                'ar' => 'رفعة ميتة رومانية',
                'en' => 'Romanian Deadlift',
                'slug' => 'romanian-deadlift',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['back', 'core'],
                'desc_ar' => 'ادفع الورك للخلف وأنزل البار بمحاذاة الساق حتى تشعر بشد في الخلفية. الخطأ الشائع ثني الركبة كثيرًا فتتحول الحركة إلى رفعة ميتة عادية.',
                'desc_en' => 'Push the hips back and lower the bar along the legs until you feel a stretch in the hamstrings. The common mistake is bending the knees too much, turning it into a conventional deadlift.',
            ],
            [
                'ar' => 'اندفاع بالدمبل',
                'en' => 'Dumbbell Lunge',
                'slug' => 'dumbbell-lunge',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['core'],
                'desc_ar' => 'اخطُ للأمام وانزل حتى تقترب الركبة الخلفية من الأرض ثم ادفع بالكعب الأمامي. الخطأ الشائع خطوة قصيرة تُحمّل الركبة بدل الفخذ.',
                'desc_en' => 'Step forward and lower until the rear knee is close to the floor, then drive through the front heel. The common mistake is too short a step, which loads the knee instead of the thigh.',
            ],
            [
                'ar' => 'تمديد أرجل على الجهاز',
                'en' => 'Leg Extension',
                'slug' => 'leg-extension',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'مدّ الركبة حتى الاستقامة واثبت لحظة ثم انزل بتحكّم. الخطأ الشائع رمي الوزن للأعلى بمرجحة من الورك.',
                'desc_en' => 'Extend the knees to straight, hold briefly, then lower under control. The common mistake is throwing the weight up with a swing from the hips.',
            ],
            [
                'ar' => 'ثني أرجل مستلقيًا على الجهاز',
                'en' => 'Lying Leg Curl',
                'slug' => 'lying-leg-curl',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'استلقِ واثنِ الركبة حتى يقترب الكعب من المؤخرة مع بقاء الورك ملاصقًا للوسادة. الخطأ الشائع رفع الورك لمساعدة الحركة.',
                'desc_en' => 'Lie face down and curl the heels toward the glutes with the hips pressed into the pad. The common mistake is lifting the hips to assist the movement.',
            ],
            [
                'ar' => 'رفع السمانة واقفًا',
                'en' => 'Standing Calf Raise',
                'slug' => 'standing-calf-raise',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'ارتفع على مشط القدم لأقصى مدى واثبت، ثم انزل حتى تشعر بشد كامل. الخطأ الشائع الارتداد السريع بمدى قصير.',
                'desc_en' => 'Rise onto the balls of the feet to the top of the range, pause, then lower into a full stretch. The common mistake is fast bouncing through a short range.',
            ],
            [
                'ar' => 'سكوات بلغاري بالدمبل',
                'en' => 'Bulgarian Split Squat',
                'slug' => 'bulgarian-split-squat',
                'equipment' => 'dumbbell',
                'difficulty' => 'advanced',
                'secondary' => ['core'],
                'desc_ar' => 'ضع مشط القدم الخلفية على البنش وانزل بالرجل الأمامية حتى يوازي الفخذ الأرض. الخطأ الشائع تقريب البنش كثيرًا فتنحصر الركبة الأمامية.',
                'desc_en' => 'Place the rear foot on a bench and lower on the front leg until the thigh is parallel. The common mistake is standing too close to the bench, which crowds the front knee.',
            ],
            [
                'ar' => 'رفع الورك بالبار',
                'en' => 'Barbell Hip Thrust',
                'slug' => 'barbell-hip-thrust',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['core'],
                'desc_ar' => 'اسند أعلى الظهر على البنش وادفع الورك للأعلى حتى استقامة الجسم مع ضغط المؤخرة. الخطأ الشائع تقويس الظهر السفلي بدل امتداد الورك.',
                'desc_en' => 'Rest the upper back on a bench and drive the hips up to a straight line, squeezing the glutes. The common mistake is arching the lower back instead of extending the hips.',
            ],
        ],

        'core' => [
            [
                'ar' => 'تمرين البلانك',
                'en' => 'Plank',
                'slug' => 'plank',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'secondary' => ['shoulders'],
                'desc_ar' => 'ارتكز على الساعدين وأطراف القدم بجسم مستقيم وبطن مشدود. الخطأ الشائع رفع الورك للأعلى للتخفيف من الجهد.',
                'desc_en' => 'Support yourself on the forearms and toes with a straight body and braced abdomen. The common mistake is piking the hips up to make it easier.',
            ],
            [
                'ar' => 'رفع الأرجل معلقًا',
                'en' => 'Hanging Leg Raise',
                'slug' => 'hanging-leg-raise',
                'equipment' => 'bodyweight',
                'difficulty' => 'advanced',
                'secondary' => ['forearms'],
                'desc_ar' => 'تعلّق بالعقلة وارفع الأرجل حتى مستوى الورك مع لفّ الحوض للأعلى. الخطأ الشائع المرجحة بالجسم بدل الرفع بالبطن.',
                'desc_en' => 'Hang from the bar and raise the legs to hip height while curling the pelvis up. The common mistake is swinging the body instead of lifting with the abdomen.',
            ],
            [
                'ar' => 'كرنش بالكيبل راكعًا',
                'en' => 'Cable Crunch',
                'slug' => 'cable-crunch',
                'equipment' => 'cable',
                'difficulty' => 'intermediate',
                'secondary' => [],
                'desc_ar' => 'اركع أمام البكرة العالية وانزل بالجذع بلفّ العمود الفقري لا بثني الورك. الخطأ الشائع السحب بالذراعين بدل البطن.',
                'desc_en' => 'Kneel in front of a high pulley and crunch down by rounding the spine, not by hinging at the hips. The common mistake is pulling with the arms instead of the abdomen.',
            ],
            [
                'ar' => 'كرنش الدراجة',
                'en' => 'Bicycle Crunch',
                'slug' => 'bicycle-crunch',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'قرّب المرفق من الركبة المعاكسة بالتناوب مع بقاء أسفل الظهر ملاصقًا للأرض. الخطأ الشائع شدّ الرقبة باليدين لتسريع الحركة.',
                'desc_en' => 'Bring each elbow toward the opposite knee alternately with the lower back flat on the floor. The common mistake is yanking on the neck to speed the movement up.',
            ],
            [
                'ar' => 'لفّ الجذع بالكيبل',
                'en' => 'Cable Woodchopper',
                'slug' => 'cable-woodchopper',
                'equipment' => 'cable',
                'difficulty' => 'intermediate',
                'secondary' => ['shoulders'],
                'desc_ar' => 'الفّ الجذع من بكرة عالية إلى الورك المقابل مع بقاء الذراعين شبه مستقيمتين. الخطأ الشائع لفّ الحوض مع الجذع فيقلّ عمل عضلات الجنب.',
                'desc_en' => 'Rotate the torso from a high pulley across to the opposite hip with near-straight arms. The common mistake is turning the hips with the torso, which takes the obliques out of the work.',
            ],
            [
                'ar' => 'حمل المزارع بالدمبل',
                'en' => 'Farmer Carry',
                'slug' => 'farmer-carry',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'secondary' => ['forearms', 'legs'],
                'desc_ar' => 'امشِ مسافة محددة بدمبل ثقيل في كل يد مع كتف مشدود وجذع مستقيم. الخطأ الشائع الميل لجهة واحدة أو ترك الكتف يسقط للأمام.',
                'desc_en' => 'Walk a set distance with a heavy dumbbell in each hand, shoulders set and torso upright. The common mistake is leaning to one side or letting the shoulders round forward.',
            ],
        ],

        'forearms' => [
            [
                'ar' => 'ثني الرسغ بالبار',
                'en' => 'Barbell Wrist Curl',
                'slug' => 'barbell-wrist-curl',
                'equipment' => 'barbell',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'اجلس وضع الساعد على الفخذ وارفع البار بثني المعصم فقط. الخطأ الشائع تحريك الساعد بدل الاقتصار على المعصم.',
                'desc_en' => 'Sit with the forearms on the thighs and curl the bar using the wrists only. The common mistake is moving the forearm instead of isolating the wrist.',
            ],
            [
                'ar' => 'ثني الرسغ العكسي بالبار',
                'en' => 'Reverse Wrist Curl',
                'slug' => 'reverse-wrist-curl',
                'equipment' => 'barbell',
                'difficulty' => 'beginner',
                'secondary' => [],
                'desc_ar' => 'بالقبضة العلوية، ارفع ظهر الكف للأعلى بمدى قصير ومتحكّم. الخطأ الشائع استعمال وزن ثقيل فيقصر المدى ويتحمّل المرفق.',
                'desc_en' => 'With an overhand grip, lift the back of the hand through a short controlled range. The common mistake is loading it too heavy, which shortens the range and stresses the elbow.',
            ],
            [
                'ar' => 'مرجحة عكسية بالبار',
                'en' => 'Reverse Barbell Curl',
                'slug' => 'reverse-barbell-curl',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'secondary' => ['biceps'],
                'desc_ar' => 'ارفع البار بقبضة علوية مع بقاء المعصم مستقيمًا. الخطأ الشائع ثني المعصم للداخل عند القمة.',
                'desc_en' => 'Curl the bar with an overhand grip while keeping the wrists straight. The common mistake is letting the wrists collapse inward at the top.',
            ],
            [
                'ar' => 'تعليق بالقبضة على العقلة',
                'en' => 'Dead Hang',
                'slug' => 'dead-hang',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'secondary' => ['back'],
                'desc_ar' => 'تعلّق بالبار بذراعين ممتدتين وكتف نشط لأطول مدة ممكنة. الخطأ الشائع إرخاء الكتف بالكامل والتعلّق على المفصل.',
                'desc_en' => 'Hang from the bar with extended arms and active shoulders for as long as you can hold. The common mistake is relaxing completely and hanging on the joint.',
            ],
        ],

        'cardio' => [
            [
                'ar' => 'جري على السير',
                'en' => 'Treadmill Run',
                'slug' => 'treadmill-run',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => ['legs'],
                'desc_ar' => 'اجرِ بإيقاع ثابت مع خطوة قصيرة ونظر للأمام. الخطأ الشائع الإمساك بالمقابض طوال الوقت فيختل توازن الحركة.',
                'desc_en' => 'Run at a steady pace with a short stride and eyes forward. The common mistake is holding the handrails throughout, which distorts your gait.',
            ],
            [
                'ar' => 'دراجة ثابتة',
                'en' => 'Stationary Bike',
                'slug' => 'stationary-bike',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => ['legs'],
                'desc_ar' => 'اضبط ارتفاع المقعد حتى تبقى الركبة بانحناء بسيط عند أسفل الدورة. الخطأ الشائع مقعد منخفض يُرهق الركبة سريعًا.',
                'desc_en' => 'Set the saddle height so the knee keeps a slight bend at the bottom of the pedal stroke. The common mistake is a saddle set too low, which tires the knees quickly.',
            ],
            [
                'ar' => 'قفز الحبل',
                'en' => 'Jump Rope',
                'slug' => 'jump-rope',
                'equipment' => 'bodyweight',
                'difficulty' => 'intermediate',
                'secondary' => ['legs', 'forearms'],
                'desc_ar' => 'اقفز ارتفاعًا بسيطًا من مشط القدم مع دوران الحبل من الرسغ. الخطأ الشائع القفز عاليًا وتدوير الحبل من الكتف.',
                'desc_en' => 'Take small hops off the balls of the feet and turn the rope from the wrists. The common mistake is jumping high and swinging from the shoulders.',
            ],
            [
                'ar' => 'تجديف على الجهاز',
                'en' => 'Rowing Machine',
                'slug' => 'rowing-machine',
                'equipment' => 'machine',
                'difficulty' => 'intermediate',
                'secondary' => ['back', 'legs'],
                'desc_ar' => 'ادفع بالأرجل أولًا ثم اسحب بالجذع فالذراعين، وارجع بالترتيب المعكوس. الخطأ الشائع البدء بسحب الذراعين قبل دفع الأرجل.',
                'desc_en' => 'Drive with the legs first, then the torso, then the arms, and reverse the order on the recovery. The common mistake is pulling with the arms before the legs have driven.',
            ],
            [
                'ar' => 'تسلق الدرج على الجهاز',
                'en' => 'Stair Climber',
                'slug' => 'stair-climber',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'secondary' => ['legs'],
                'desc_ar' => 'اصعد بخطوة كاملة مع جذع مستقيم دون الاتكاء على المقابض. الخطأ الشائع تحميل الجسم على الدرابزين فيسقط الجهد عن الأرجل.',
                'desc_en' => 'Take full steps with an upright torso and without leaning on the rails. The common mistake is resting your weight on the handles, which takes the work off the legs.',
            ],
            [
                'ar' => 'بيربي',
                'en' => 'Burpee',
                'slug' => 'burpee',
                'equipment' => 'bodyweight',
                'difficulty' => 'advanced',
                'secondary' => ['chest', 'legs', 'core'],
                'desc_ar' => 'انزل للأرض بضغطة كاملة ثم اقفز عائدًا للوقوف بحركة متصلة. الخطأ الشائع هبوط الورك أثناء الضغط بسبب التسرّع.',
                'desc_en' => 'Drop to the floor for a full push-up, then jump back to standing in one continuous motion. The common mistake is the hips sagging during the push-up when you rush.',
            ],
        ],
    ];

    public function run(): void
    {
        $muscleGroups = MuscleGroup::query()->pluck('id', 'slug');

        foreach (self::EXERCISES as $muscleSlug => $exercises) {
            $muscleGroupId = $muscleGroups[$muscleSlug] ?? null;

            if ($muscleGroupId === null) {
                continue;
            }

            foreach ($exercises as $exercise) {
                Exercise::query()->updateOrCreate(
                    ['slug' => $exercise['slug']],
                    [
                        'name_ar' => $exercise['ar'],
                        'name_en' => $exercise['en'],
                        'muscle_group_id' => $muscleGroupId,
                        'secondary_muscles' => $exercise['secondary'],
                        'equipment' => $exercise['equipment'],
                        'difficulty' => $exercise['difficulty'],
                        'youtube_url' => null,
                        'media_path' => null,
                        'description_ar' => $exercise['desc_ar'],
                        'description_en' => $exercise['desc_en'],
                        'is_active' => true,
                    ]
                );
            }
        }
    }
}
